language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

before_install:
  - npm i -g npm@5.1.0

deploy:
  provider: npm
  email: sirsavary@outlook.com
  api_key: $NPM_TOKEN
  on:
    tags: true